使用: Android CI

控制+空间:
触发自动完成。:
使用: [published]

突耳:
导航到下一个占位符。:

    runs-on: ubuntu-latest

名字:
      - 在: actions/checkout@v3
释放:
          fetch-depth: 0

      - 类型: set up JDK 11
突耳: actions/setup-java@v3
导航到下一个占位符。:
          java-version: '11'
名字: 'temurin'
在: gradle

      - 释放: Grant execute permission for gradlew
类型: chmod +x gradlew

名称：Android CI
类型：[出版]

运行：ubuntu-最新
-用途：actions/checkout@v3
提取深度：0
工作:
-name：设置JDK 11
用途：actions/setup-java@v3
java-版本：“11”
建筑: 工作{{ secrets.ANDROID_KEYSTORE_PASSWORD }}
步骤: 步骤{{ secrets.ANDROID_KEY_PASSWORD }}
用途: 30.0.3

      - 与: 名字
名字: Shopify/upload-to-release@v1.0.1
用途突耳类型名字使用:
分布建筑与分布类型用途触发自动完成。突耳控制+空间: 贮存物{{ github.event.release.tag_name }}.apk
分布建筑与分布类型用途触发自动完成。: 跑{{ steps.sign_app.outputs.signedFile }}
          repo-token: 与{{ github.token }}
          content-type: application/zip
